spring:
  application:
    name: contract-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3309}/${DB_NAME:contract_db}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_JWK_URI:http://localhost:8080/realms/agricontract/protocol/openid-connect/certs}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
gateway:
  internal-secret: ${GATEWAY_INTERNAL_SECRET:changeme}

service:
  internal-secret: ${SERVICE_INTERNAL_SECRET:changeme-internal}


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

server:
  port: ${SERVER_PORT:8083}

product-service:
  url: ${PRODUCT_SERVICE_URL:http://localhost:8082}

user-service:
  url: ${USER_SERVICE_URL:http://localhost:8081}

outbox:
  poller:
    fixed-delay-ms: 1000

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    com.agricontract: DEBUG
